### ISSUE TITLE
PR and Issue description.

### ISSUE THREAD

**Issue by FarahZaqout** [GSG-K3/360HMR#30]
Hey guys, make sure you add adequate description text to your future PRs and issues.

**Comment by karmelyoei** [comment]
ok I agree to do that for issues but for the PR I don't think that is necessary cause I will attach it to the related issue since we don't have time and we are already late due to design so I don't wanna waste more time for any extra documentation

**Comment by mantagen** [comment]
https://github.com/GSG-K3/360HMR/pull/40

I've created a "pull request template".
@karmelyoei I think it's important that the code reviewer can understand _how to test_ your PR.
Because when you review a pull request, you should
1. review the code
2. pull down and test the functionality
