### ISSUE TITLE
new employee

### ISSUE THREAD

**Issue by rubasider** [GSG-K3/360HMR#56]
## New employee tap 

- [ ] Route ` /dashboard`

---

- [ ] Description 
### You can see:

- img

- 3 text fields for name ,email and date of hiring
- selector to select position
- button to confirm adding process

- [ ] UI
![Insert the new employee](https://user-images.githubusercontent.com/32986134/87437808-6fb5c980-c5f7-11ea-9cd7-4796423c08ff.png)

**Comment by karmelyoei** [comment]
Done
